from beneficio import Beneficio
persona = Beneficio("andres", "mafla","1193570753", 23, 1000000) 
print("-----------------------------------")
print(persona.detalle())
print("-----------------------------------")
print(persona.ingresar(100000))
print("-----------------------------------")
print(persona.retirar(50000))
print("-----------------------------------")
print(persona.retirar(-8))
print("-----------------------------------")
print(persona.retirar(5000000))
print("-----------------------------------")
print(persona.ingresar(-10000))
print("-----------------------------------")
print(persona.mostrar())
